## Base Configuration
server:
  port: 5000

spring:
  application:
    name: demo-api.user
  datasource:
    url: jdbc:postgresql://localhost:5432/test
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: proba123
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: POSTGRESQL
  flyway:
    url: jdbc:postgresql://localhost:5432/test
    baseline-on-migrate: true
    user: postgres
    password: proba123
    baseline-description: "init"
    baseline-version: 0
logging:
  level:
    org.springframework: DEBUG

demo-api:
  # The key MUST be overwritten in production
  user:
    token:
      jwtSecretKey                : "b77584f919bc88a5343dd24374f6fc1af0d0dfb907e8783911f1d7bf3771a752d8a72dc69434665bb6f3cdd416b152d626544fce9840cf67718ece0dd28a1cb8"
      tokenTtlDays                : 7
      activationTokenTtlDays      : 1
      tokenCacheTtlSeconds        : 60
      tokenCacheMaxSize           : 1000
      webTokenTtlMinutes          : 1800
      activationNumberTtlSeconds  : 300
      activationNumberLength      : 6
  cors:
    allowed-origins: "**"
  email:
    from: meho.aliefendic@gmail.com
cloud:
  aws:
    region:
      static: eu-north-1
    credentials:
      accessKey: AKIAQFS65AH6DPEURM42
      secretKey: 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
      instanceProfile: false
    stack:
      auto: false